### ISSUE TITLE
Location from timestamp

### ISSUE THREAD

**Issue by LolowaK** [nyuad-astroparticle/raad#2]
# Description

We need a function that takes in a timestamp and returns the location of light-1 at that time so that we can fix the timestamp completely.

To do this, we will create a linear function that takes two points and finds the exact time and location for the point in between.

# To do list

- [x] Write a python script that takes in a location file, and splits it
- [x] Write a function that takes in a timestamp and returns the appropriate file where the timestamp belongs to
- [x] Write a function that takes in a timestamp (event) and loads the corresponding location
- [x] Write a function that takes in an array (raadpy array) of timestamps and returns an array of the corresponding location (raadpy array)

```python
type(i) == rp.event
```

# Active Jupyter Notebook

[https://github.com/nyuad-astroparticle/raad/blob/main/Data_Analysis/Location/Location_from_Timestamp.ipynb](https://github.com/nyuad-astroparticle/raad/blob/main/Data_Analysis/Location/Location_from_Timestamp.ipynb)

**Comment by PanosEconomou** [comment]
Fixed by @DanishKhan2025 in this pull-request on [https://github.com/nyuad-astroparticle/raadpy/pull/3](https://github.com/nyuad-astroparticle/raadpy/pull/3)
