### ISSUE TITLE
Downloading Data from NA

### ISSUE THREAD

**Issue by LolowaK** [nyuad-astroparticle/raad#3]
# To do list

- [x] Pull data from NanoAvionics
- [x] Read instead of downloading the data
- [x] Split data pulled into different values
- [x] Define a function to do the above

# Active Jupyter Notebook
> [https://github.com/nyuad-astroparticle/raad/blob/main/Data_Analysis/Data_Download/Data_Download_from_NA.ipynb](https://github.com/nyuad-astroparticle/raad/blob/main/Data_Analysis/Data_Download/Data_Download_from_NA.ipynb)

**Comment by PanosEconomou** [comment]
Fixed
